### ISSUE TITLE
social share icons aanpassen

### ISSUE THREAD

**Issue by janwillemhdegraaf** [jeroenbreen/025-ventu#14]
social share icons aanhouden volgens zeplin in zeppli zijn wel de teksten niet correct in combi met de iconen.

**Comment by jeroenbreen** [comment]
bedoel je deze?
![screen shot 2017-06-28 at 14 44 58](https://user-images.githubusercontent.com/6692653/27637543-644ad710-5c10-11e7-9e2c-0f95566f1b95.png)

**Comment by janwillemhdegraaf** [comment]
![image](https://user-images.githubusercontent.com/29629838/27786494-a511ad76-5fe1-11e7-9852-4b2ade362692.png)
