### ISSUE TITLE
Niet klikbare pijl Dialog >> ligt aan resize!

### ISSUE THREAD

**Issue by janwillemhdegraaf** [jeroenbreen/025-ventu#15]
wizzard werkt niet omdat de "pijl" niet klikbaar is

**Comment by jeroenbreen** [comment]
@janwillemhdegraaf heb je een screenshot? Of was dit na een resize / tabletrotatie?

**Comment by janwillemhdegraaf** [comment]
dit is het standaard demo laptop formaat van de verkopers van Ventu. als je full screen kijkt, loopt de geanimeerde pijl in de wizzard door de overige iconen op het scherm.
