### ISSUE TITLE
Nieuw icoon  'Group' ontwerpen

### ISSUE THREAD

**Issue by jeroenbreen** [jeroenbreen/025-ventu#2]
Dit icoontje heb ik snel ontworpen, idealiter zou Liza die nog doen.

<img width="368" alt="screen shot 2017-06-22 at 15 13 43" src="https://user-images.githubusercontent.com/6692653/27435770-6b50bb5e-575d-11e7-8dfb-c7b920b38399.png">

**Comment by janwillemhdegraaf** [comment]
Liza heeft nieuwe dingen in Zeplin gezet

**Comment by jeroenbreen** [comment]
@janwillemhdegraaf ik zie niks nieuws in Zeplin, laatste updates zijn van 31 dagen geleden.

**Comment by janwillemhdegraaf** [comment]
we laten het hierbij
