### ISSUE TITLE
Makelaar avatar

### ISSUE THREAD

**Issue by jeroenbreen** [jeroenbreen/025-ventu#27]
Doen we hier iets mee, moeten we er iets mee doen?
https://app.zeplin.io/project/59083b2805ae64fb4eb33adb/screen/592425c8d777979725c46ef9

(zijn mooie avatars)

**Comment by janwillemhdegraaf** [comment]
hebben we inmiddels in de widget (ventu in huisstijlkleuren van een makelaar) gezet
