### ISSUE TITLE
Aanwijzing altijd zichtbaar?

### ISSUE THREAD

**Issue by jeroenbreen** [jeroenbreen/025-ventu#29]
Is de aanwijzing bij het labeltje altijd zichtbaar:

<img width="119" alt="screen shot 2017-07-17 at 15 56 36" src="https://user-images.githubusercontent.com/6692653/28271360-990c0bd4-6b08-11e7-8ed5-d67343d59985.png">

**Comment by janwillemhdegraaf** [comment]
nee ik zou deze nadat je hebt in/uitgeschoven het labeltje verbergen
